### ISSUE TITLE
Links standout a little too much

### ISSUE THREAD

**Issue by punchagan** [punchagan/er#2]
right now, they're blue in light theme, and yellow in dark theme -- which stand out a little too much. I want people ot be able to focus on the reading, and not be distracted by the links.  

(the main color in the background of the site title is a contender?)

**Comment by kamalx** [comment]
Yes, it is. Good thing about that color is that it can potentially work for both light and dark themes. No color switching required for links.

**Comment by punchagan** [comment]
![image](https://github.com/user-attachments/assets/fa4dc47d-2861-4440-b51b-41bcb91f93a9)

![image](https://github.com/user-attachments/assets/d2c5bc28-1d1d-4176-91f6-a3adddbe9db8)

Link style on posts are different from the link style on the home page.
