### ISSUE TITLE
Fix styling of the "intro" paragraph/section

### ISSUE THREAD

**Issue by punchagan** [punchagan/er#5]
![image](https://github.com/user-attachments/assets/9aa9a965-65cd-4dfa-8820-94880b5e0472)

spacing/size/typography/etc

**Comment by kamalx** [comment]
Following are the suggested changes for this section's visual presentation.

![image](https://github.com/user-attachments/assets/2ecd576e-c684-45bc-ae70-b1be431e1165)
![image](https://github.com/user-attachments/assets/51de6942-bd0f-42d6-ab85-da974d2c6263)
