### ISSUE TITLE
Change styling of tags?

### ISSUE THREAD

**Issue by punchagan** [punchagan/er#6]
![image](https://github.com/user-attachments/assets/b1afb296-491b-47c0-b8d8-6397a7540dc8)

`tags: [ xxx yyy zzz]` -> I think this could be improved. may be get rid of `tags:` and `[ ]` and add a subtle underline?

**Comment by kamalx** [comment]
I've made some changes to tag presentation. How do you find this?

![image](https://github.com/user-attachments/assets/d39e04bc-ab44-47c0-94d3-87b593c014ce)

**Comment by kamalx** [comment]
Here's another version without the icon and decorations for the links.
![image](https://github.com/user-attachments/assets/2f88a275-d8d9-43ca-bd9b-bc1fc5d0cf13)
